# Generated by Django 4.0.1 on 2022-01-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastes',
            options={'verbose_name_plural': 'Pastes'},
        ),
    ]
