# Generated by Django 3.2.12 on 2022-02-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0002_alter_pastes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastes',
            name='encrypted_flag',
            field=models.BooleanField(default=False),
        ),
    ]
